version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "isort"

[[transformers]]
name = "black"
